#!/bin/bash

# This script is meant to be run after Pycharm's "test_lc_ble",
# which is a run configuration. Since BLE requires root permissions,
# the "htmlcov" folder generated by "test_lc_ble" has root file
# permissions, too. This script copies and reowns "htmlcov" so
# a normal user can check report results without using a web
# browser with root permissions which, by the way, is difficult.
# You can run several scripts via the "multirun" Pycharm plugin.

me=`basename "$0"`
currentdir=`pwd`
dfolder=`echo /home/kaz/Downloads/htmlcov`
doesfileexist="./bash_scripts/flag_to_run"

echo "Running $me..."
echo "My current working directory is: $currentdir"
# if test -f $doesfileexist; then
#    echo "Do this in the future"
# fi
echo "Copying htmlcov folder to $dfolder..."
cp -rf tests/htmlcov/. $dfolder
chown -R kaz:kaz $dfolder


